<?php //$_streetValidationClass = trim(str_replace(
//            'required-entry',
//            '',
//            $this->helper('customer/address')->getAttributeValidationClass('street')
//        )); ?>
<?php //for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
<!--    <li class="wide">-->
<!--        <label for="street_--><?php //echo $_i ?><!--" class="required"><em>*</em>--><?php //echo $this->__($this->getStreetLabel($_i)) ?><!--</label>-->
<!--        <div class="input-box">-->
<!--            <input type="text" name="street[]" value="--><?php //echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?><!--" title="--><?php //echo $this->__('Street Address %s', $_i) ?><!--" id="street_--><?php //echo $_i ?><!--" class="input-text --><?php //echo $_streetValidationClass ?><!--" />-->
<!--        </div>-->
<!--    </li>-->
<?php //endfor; ?>